# Generated by Django 3.2.9 on 2021-11-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=120)),
                ('Data_Nasc', models.DateField()),
                ('CPF', models.CharField(max_length=13)),
                ('RG', models.CharField(max_length=10)),
                ('Telefone', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
